### ISSUE TITLE
无法发送音乐

### ISSUE THREAD

**Issue by 343224777** [zzseki/QChatGPT_Plugin_Music#2]
[2024-09-22 22:10:32.352] /app/pkg/provider/tools/toolmgr.py (122) - [ERROR] :
    执行函数 Webwlkr-access_the_web 时发生错误: WebwlkrPlugin._() missing 2 required positional arguments: 'url' and 'brief_len'
Traceback (most recent call last):
  File "/app/pkg/provider/tools/toolmgr.py", line 120, in execute_func_call
    return await function.func(plugin, **parameters)
  File "/app/pkg/plugin/loaders/classic.py", line 110, in handler
    return func(*args, **kwargs)
TypeError: WebwlkrPlugin._() missing 2 required positional arguments: 'url' and 'brief_len'
[2024-09-22 22:10:32.363] /app/pkg/pipeline/process/handlers/chat.py (79) - [INFO] :
    对话(0)响应: tool: "error occurre...
[2024-09-22 22:10:33.920] /app/pkg/pipeline/process/handlers/chat.py (79) - [INFO] :
    对话(0)响应: assistant: 我无法直接播放音乐...
[2024-09-22 22:10:46.779] /app/pkg/pipeline/process/process.py (42) - [INFO] :
    处理 person_1319579090 的请求(1): 播放音乐：只因你太美
[2024-09-22 22:10:49.763] /app/plugins/QChatGPT_Plugin_Music/main.py (34) - [INFO] :
    http://m7.music.126.net/20240922223549/b25ecb13204e710e279ba8dd6071c60e/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/14052039708/e2eb/05ab/8883/a5b17b44184be211af4934e1d27be057.mp3
[2024-09-22 22:10:58.876] /app/plugins/QChatGPT_Plugin_Music/main.py (42) - [INFO] :
    播放音乐：只因你太美
[2024-09-22 22:10:59.016] /app/pkg/pipeline/controller.py (167) - [ERROR] :
    处理请求时出错 query_id=1 stage=SendResponseBackStage : <ActionFailed status='failed', retcode=1200, data=None, message='Error: 文件下载失败未知文件类型\n    at OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:29993:13)\n    at async Object.record (file:///app/napcat/napcat.mjs:29701:8)\n    at async Promise.all (index 0)\n    at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:29935:17)\n    at async SendMsg._handle (file:///app/napcat/napcat.mjs:36707:52)\n    at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36607:23)\n    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:12792:21)', wording='Error: 文件下载失败未知文件类型\n    at OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:29993:13)\n    at async Object.record (file:///app/napcat/napcat.mjs:29701:8)\n    at async Promise.all (index 0)\n    at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:29935:17)\n    at async SendMsg._handle (file:///app/napcat/napcat.mjs:36707:52)\n    at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36607:23)\n    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:12792:21)', echo={'seq': 3}>

**Comment by zzseki** [comment]
是否安装了其他插件，前面的报错好像不是该插件的问题，另外关于无法下载音乐的问题，请你再请求一次并查看链接是否有效能否手动下载，注意插件目录中是否有名为"temp"的文件夹，没有的话要手动创建一下否则会报错

**Comment by 343224777** [comment]
> 是否安装了其他插件，前面的报错好像不是该插件的问题，另外关于无法下载音乐的问题，请你再请求一次并查看链接是否有效能否手动下载，注意插件目录中是否有名为"temp"的文件夹，没有的话要手动创建一下否则会报错

请求多次，API那里是OK的，也能够手动下载，目录中也有temp文件夹，但是就是发不了语音

**Comment by zzseki** [comment]
感觉不像是这个插件的报错，是不是安装了其他插件冲突了，我试了一下我这里没问题

**Comment by zzseki** [comment]
你看看temp文件夹中的temp.wav是不是你要的音乐

**Comment by tyrantcwj** [comment]
![165494577eb38d8baeca00e4ae8183f4](https://github.com/user-attachments/assets/32c85ba8-3ee7-4b73-bba8-420b3e57d968)
同样的情况，temp.wav是林俊杰的愿与愁，试了两三首都失败

**Comment by zzseki** [comment]
不应该啊，因为这显示的好像不是我这个插件的报错，你把其他的插件关掉试试

**Comment by zzseki** [comment]
我更新了一下代码，你卸载插件重新安装并配置试试看还有没有报错
